version: "3.3"

services:

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:16.1.1
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    restart: always
    volumes:
      - keycloak_data:/data
      - keycloak_data:/opt/jboss/keycloak/providers
      - keycloak_data:/opt/jboss/keycloak/standalone/configuration

volumes:
  keycloak_data: