version: "3.9"

services:

  pg-db:
    image: marceloeugenios/deposito-db:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: pgadmin
#    environment:
#       - PGADMIN_DEFAULT_EMAIL=admin@deposito.dev
#       - PGADMIN_DEFAULT_PASSWORD=admin
#    ports:
#       - "5555:80"

#volumes:
#  keycloak_data: