version: "3.9"

services:

  deposito-db:
    image: marceloeugenios/deposito-db:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  deposito-app:
    image: marceloeugenios/deposito-app:latest
    ports:
      - "8080:8080"
    depends_on:
      - deposito-db