create TABLE bebida
             (
                          id          INTEGER generated BY DEFAULT AS identity,
                          bebida_tipo VARCHAR(100) NOT NULL,
                          nome        VARCHAR(200) NOT NULL,
                          situacao    VARCHAR(50) NOT NULL,
                          _marca INTEGER NOT NULL,
                          PRIMARY KEY (id)
             );
             create TABLE marca
             (
                          id       INTEGER generated BY DEFAULT AS identity,
                          nome     VARCHAR(200) NOT NULL,
                          situacao VARCHAR(20) NOT NULL,
                          PRIMARY KEY (id)
             );
             create TABLE movimentacao
             (
                           id          bigint generated BY DEFAULT AS identity,
                          _bebida INTEGER NOT NULL,
                          data_movimentacao TIMESTAMP NOT NULL,
                          _secao         INTEGER NOT NULL,
                          tipo_movimentacao VARCHAR(20) NOT NULL,
                          volume NUMERIC(5,2) NOT NULL,
                          usuario_id     UUID NOT NULL
             );
             create TABLE secao
             (
                          id         INTEGER generated BY DEFAULT AS identity,
                          nome       VARCHAR(200) NOT NULL,
                          situacao   VARCHAR(20) NOT NULL,
                          PRIMARY KEY (id)
             );

alter table if exists secao add column ultima_alteracao timestamp;
alter table if exists secao add column version int4;

create sequence bebida_seq start 20 increment 1;
create sequence marca_seq start 20 increment 1;
create sequence movimentacao_seq start 20 increment 1;
create sequence secao_seq start 20 increment 1;

alter table marca add CONSTRAINT uk_4stchabjtotdx8kwixma6ebyf UNIQUE (nome);
alter table secao add CONSTRAINT uk_1ia7ateuo17fvobywl5n3ewji UNIQUE (nome);
alter table bebida add CONSTRAINT fkod6h56y7p9f8yrdatltng6phf FOREIGN KEY (_marca) REFERENCES marca;
alter table movimentacao add CONSTRAINT fkjqiqwqoakwsw8ycbwej7nhxig FOREIGN KEY (_bebida) REFERENCES bebida;
alter table movimentacao add constraint FK4s6074gqged88ke16g701pfkm foreign key (_secao) references secao;